version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the anuglar application...
      - ng build -c production
  post_build:
    commands:
      - echo Build completed. Artifact are being prepared...

artifactPaths:
  - build/**/*
  
cache:
  paths:
    - node_modules/**/*
